print("please enter your name")
name = input("your name: ")
print("please enter your age")
age = input("your age: ")
print("please enter your phone number")
phone = input("your phone number: ")
print("your name is", name)
print("your age is", age)
print("your phone number is", phone)
print()
print('    .""".')
print("   :_____:")
print("   |     |")
print("   |     |")
print("   | Tim |")
print("  /|     |\\")
print(" /_|_____|_\\")
print("   / \\ / \\")
print('   """ """')
print()
print("10 other programming languages:")
print("Javascript")
print("Go")
print("Java")
print("Kotlin")
print("PHP")
print("C#")
print("Swift")
print("Ruby")
print("Rust")
print("Perl")