hero1 = input('1st hero, please enter your name: ')
things1= input('now, name 3 things you will take with yourself for campaign: ')
hero2 = input('2nd hero, please enter your name: ')
things2 = input('now, name 3 things you will take with yourself for campaign: ')
hero3 = input('3rd hero, please enter your name: ')
things3 = input('now, name 3 things you will take with yourself for campaign: ')
hero4 = input('4th hero, please enter your name: ')
things4 = input('now, name 3 things you will take with yourself for campaign: ')
print(hero1)
print('took to campaign')
print(things1)
print(hero2)
print('took to campaign')
print(things2)
print(hero3)
print('took to campaign')
print(things3)
print(hero4)
print('took to campaign')
print(things4)
user_hero = int(input("how many heroes do you have in your team? (max. 5 heroes)"))
if user_hero == 1:
    hero1 = input('1st hero, please enter your name: ')
    thing1 = input('now, name 3 things you will take with yourself for campaign: ')
    print(hero1)
    print('took to campaign')
    print(thing1)
elif user_hero == 2:
    hero1 = input('1st hero, please enter your name: ')
    thing1 = input('now, name 3 things you will take with yourself for campaign: ')
    hero2 = input('2nd hero, please enter your name: ')
    thing2 = input('now, name 3 things you will take with yourself for campaign: ')

    print(hero1)
    print('took to campaign')
    print(thing1)
    print(hero2)
    print('took to campaign')
    print(thing2)
elif user_hero == 3:
    hero1 = input('1st hero, please enter your name: ')
    thing1 = input('now, name 3 things you will take with yourself for campaign: ')
    hero2 = input('2nd hero, please enter your name: ')
    thing2 = input('now, name 3 things you will take with yourself for campaign: ')
    hero3 = input('3rd hero, please enter your name: ')
    thing3 = input('now, name 3 things you will take with yourself for campaign: ')
    print(hero1)
    print('took to campaign')
    print(thing1)
    print(hero2)
    print('took to campaign')
    print(thing2)
    print(hero3)
    print('took to campaign')
    print(thing3)
elif user_hero == 4:
    hero1 = input('1st hero, please enter your name: ')
    thing1 = input('now, name 3 things you will take with yourself for campaign: ')
    hero2 = input('2nd hero, please enter your name: ')
    thing2 = input('now, name 3 things you will take with yourself for campaign: ')
    hero3 = input('3rd hero, please enter your name: ')
    thing3 = input('now, name 3 things you will take with yourself for campaign: ')
    hero4 = input('4th hero, please enter your name: ')
    thing4 = input('now, name 3 things you will take with yourself for campaign: ')
    print(hero1)
    print('took to campaign')
    print(thing1)
    print(hero2)
    print('took to campaign')
    print(thing2)
    print(hero3)
    print('took to campaign')
    print(thing3)
    print(hero4)
    print('took to campaign')
    print(thing4)
elif user_hero == 5:
    hero1 = input('1st hero, please enter your name: ')
    thing1 = input('now, name 3 things you will take with yourself for campaign: ')
    hero2 = input('2nd hero, please enter your name: ')
    thing2 = input('now, name 3 things you will take with yourself for campaign: ')
    hero3 = input('3rd hero, please enter your name: ')
    thing3 = input('now, name 3 things you will take with yourself for campaign: ')
    hero4 = input('4th hero, please enter your name: ')
    thing4 = input('now, name 3 things you will take with yourself for campaign: ')
    hero5 = input('5th hero, please enter your name: ')
    thing5 = input('now, name 3 things you will take with yourself for campaign: ')
    print(hero1)
    print(hero1)
    print('took to campaign')
    print(thing1)
    print(hero2)
    print('took to campaign')
    print(thing2)
    print(hero3)
    print('took to campaign')
    print(thing3)
    print(hero4)
    print('took to campaign')
    print(thing4)
    print(hero5)
    print('took to campaign')
    print(thing5)

else:
    print("too many players!")


