hero1 = input('1st hero, please enter your name: ')
things1= input('now, name 3 things you will take with yourself for campaign: ')
hero2 = input('2nd hero, please enter your name: ')
things2 = input('now, name 3 things you will take with yourself for campaign: ')
hero3 = input('3rd hero, please enter your name: ')
things3 = input('now, name 3 things you will take with yourself for campaign: ')
hero4 = input('4th hero, please enter your name: ')
things4 = input('now, name 3 things you will take with yourself for campaign: ')
print(hero1)
print('took to campaign')
print(things1)
print(hero2)
print('took to campaign')
print(things2)
print(hero3)
print('took to campaign')
print(things3)
print(hero4)
print('took to campaign')
print(things4)

